// Placeholder for OpenAPI export from Zod schemas.
//
// Until backend-ts is cut over as the production service, the existing
// `backend/openapi.json` (generated by the FastAPI service) remains the source
// of truth for `npm run generate:types` in the frontend. The TS service
// implements the same paths and response shapes, so the frontend client stays
// in sync with no regeneration needed.
//
// At cutover (sequence step 13), replace this script with a real implementation:
//   - Refactor routes to use @hono/zod-openapi's `createRoute` + `OpenAPIHono`
//   - Emit `openapi.json` from `app.getOpenAPIDocument(...)`
//   - Update root package.json `generate:types` to point at this file
//
// For now, fail loudly so anyone running it knows it's not implemented.
console.error('OpenAPI export from backend-ts is not yet implemented.');
console.error('Use the existing backend/openapi.json (FastAPI-generated) for frontend type generation.');
process.exit(1);
