"""initial_schema

Revision ID: 05607a464723
Revises:
Create Date: 2026-04-27 16:40:09.666417
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05607a464723"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ammunitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wiki_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ammunitions_name"), "ammunitions", ["name"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wiki_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=False)
    op.create_table(
        "factions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("discontinued", sa.Boolean(), nullable=False),
        sa.Column("logo", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_factions_slug"), "factions", ["slug"], unique=True)
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wiki_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=False)
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_army", sa.Integer(), nullable=True),
        sa.Column("isc", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("raw_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_isc"), "units", ["isc"], unique=True)
    op.create_index(op.f("ix_units_name"), "units", ["name"], unique=False)
    op.create_index(op.f("ix_units_slug"), "units", ["slug"], unique=True)
    op.create_table(
        "weapons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("wiki_url", sa.String(), nullable=True),
        sa.Column("weapon_type", sa.String(), nullable=True),
        sa.Column("burst", sa.String(), nullable=True),
        sa.Column("damage", sa.String(), nullable=True),
        sa.Column("saving", sa.String(), nullable=True),
        sa.Column("saving_num", sa.String(), nullable=True),
        sa.Column("ammunition_id", sa.Integer(), nullable=True),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("distance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapons_name"), "weapons", ["name"], unique=False)
    op.create_table(
        "fireteam_charts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=False),
        sa.Column(
            "chart_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["faction_id"], ["factions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("faction_id"),
    )
    op.create_table(
        "loadouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("profile_group_id", sa.Integer(), nullable=False),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("swc", sa.Float(), nullable=False),
        sa.Column(
            "skills_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "equipment_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "weapons_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "orders_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("profile_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mov_1", sa.Integer(), nullable=False),
        sa.Column("mov_2", sa.Integer(), nullable=False),
        sa.Column("cc", sa.Integer(), nullable=False),
        sa.Column("bs", sa.Integer(), nullable=False),
        sa.Column("ph", sa.Integer(), nullable=False),
        sa.Column("wip", sa.Integer(), nullable=False),
        sa.Column("arm", sa.Integer(), nullable=False),
        sa.Column("bts", sa.Integer(), nullable=False),
        sa.Column("wounds", sa.Integer(), nullable=False),
        sa.Column("silhouette", sa.Integer(), nullable=False),
        sa.Column("is_structure", sa.Boolean(), nullable=False),
        sa.Column("unit_type", sa.Integer(), nullable=True),
        sa.Column(
            "skills_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "equipment_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "weapons_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "unit_factions",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("faction_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["faction_id"], ["factions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("unit_id", "faction_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_factions")
    op.drop_table("profiles")
    op.drop_table("loadouts")
    op.drop_table("fireteam_charts")
    op.drop_index(op.f("ix_weapons_name"), table_name="weapons")
    op.drop_table("weapons")
    op.drop_index(op.f("ix_units_slug"), table_name="units")
    op.drop_index(op.f("ix_units_name"), table_name="units")
    op.drop_index(op.f("ix_units_isc"), table_name="units")
    op.drop_table("units")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_factions_slug"), table_name="factions")
    op.drop_table("factions")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_ammunitions_name"), table_name="ammunitions")
    op.drop_table("ammunitions")
    # ### end Alembic commands ###
