"""add_description_to_army_lists

Revision ID: a8b1e6760b9c
Revises: 76b09176587c
Create Date: 2026-04-29 15:34:54.152455
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8b1e6760b9c"
down_revision: str | None = "76b09176587c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("army_lists", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("army_lists", "description")
    # ### end Alembic commands ###
