"""add_tags_to_army_lists

Revision ID: abb83885459e
Revises: a8b1e6760b9c
Create Date: 2026-04-29 18:18:32.621391
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abb83885459e"
down_revision: str | None = "a8b1e6760b9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "army_lists",
        sa.Column("tags", sa.ARRAY(sa.String()), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("army_lists", "tags")
    # ### end Alembic commands ###
