import { pgTable, varchar, uniqueIndex, index, serial, integer, jsonb, foreignKey, unique, boolean, doublePrecision, timestamp, text, primaryKey } from "drizzle-orm/pg-core"
// `sql` import omitted — generated by drizzle-kit but unused in this snapshot.



export const alembic_version = pgTable("alembic_version", {
	version_num: varchar({ length: 32 }).primaryKey().notNull(),
});

export const units = pgTable("units", {
	id: serial().primaryKey().notNull(),
	id_army: integer(),
	isc: varchar().notNull(),
	name: varchar().notNull(),
	slug: varchar().notNull(),
	logo: varchar(),
	raw_json: jsonb().notNull(),
}, (table) => [
	uniqueIndex("ix_units_isc").using("btree", table.isc.asc().nullsLast().op("text_ops")),
	index("ix_units_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
	uniqueIndex("ix_units_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
]);

export const skills = pgTable("skills", {
	id: serial().primaryKey().notNull(),
	name: varchar().notNull(),
	wiki_url: varchar(),
}, (table) => [
	index("ix_skills_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const equipment = pgTable("equipment", {
	id: serial().primaryKey().notNull(),
	name: varchar().notNull(),
	wiki_url: varchar(),
}, (table) => [
	index("ix_equipment_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const ammunitions = pgTable("ammunitions", {
	id: serial().primaryKey().notNull(),
	name: varchar().notNull(),
	wiki_url: varchar(),
}, (table) => [
	index("ix_ammunitions_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const fireteam_charts = pgTable("fireteam_charts", {
	id: serial().primaryKey().notNull(),
	faction_id: integer().notNull(),
	chart_json: jsonb().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.faction_id],
			foreignColumns: [factions.id],
			name: "fireteam_charts_faction_id_fkey"
		}).onDelete("cascade"),
	unique("fireteam_charts_faction_id_key").on(table.faction_id),
]);

export const factions = pgTable("factions", {
	id: serial().primaryKey().notNull(),
	parent_id: integer(),
	name: varchar().notNull(),
	slug: varchar().notNull(),
	discontinued: boolean().notNull(),
	logo: varchar().notNull(),
}, (table) => [
	uniqueIndex("ix_factions_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
]);

export const loadouts = pgTable("loadouts", {
	id: serial().primaryKey().notNull(),
	unit_id: integer().notNull(),
	profile_group_id: integer().notNull(),
	option_id: integer().notNull(),
	name: varchar().notNull(),
	points: integer().notNull(),
	swc: doublePrecision().notNull(),
	skills_json: jsonb().notNull(),
	equipment_json: jsonb().notNull(),
	weapons_json: jsonb().notNull(),
	orders_json: jsonb(),
}, (table) => [
	foreignKey({
			columns: [table.unit_id],
			foreignColumns: [units.id],
			name: "loadouts_unit_id_fkey"
		}).onDelete("cascade"),
]);

export const profiles = pgTable("profiles", {
	id: serial().primaryKey().notNull(),
	unit_id: integer().notNull(),
	profile_group_id: integer().notNull(),
	name: varchar().notNull(),
	mov_1: integer().notNull(),
	mov_2: integer().notNull(),
	cc: integer().notNull(),
	bs: integer().notNull(),
	ph: integer().notNull(),
	wip: integer().notNull(),
	arm: integer().notNull(),
	bts: integer().notNull(),
	wounds: integer().notNull(),
	silhouette: integer().notNull(),
	is_structure: boolean().notNull(),
	unit_type: integer(),
	skills_json: jsonb().notNull(),
	equipment_json: jsonb().notNull(),
	weapons_json: jsonb().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.unit_id],
			foreignColumns: [units.id],
			name: "profiles_unit_id_fkey"
		}).onDelete("cascade"),
]);

export const weapons = pgTable("weapons", {
	id: serial().primaryKey().notNull(),
	name: varchar().notNull(),
	wiki_url: varchar(),
	weapon_type: varchar(),
	burst: varchar(),
	damage: varchar(),
	saving: varchar(),
	saving_num: varchar(),
	ammunition_id: integer(),
	properties: jsonb(),
	distance: jsonb(),
}, (table) => [
	index("ix_weapons_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
]);

export const ai_usage = pgTable("ai_usage", {
	id: serial().primaryKey().notNull(),
	user_id: varchar().notNull(),
	year_month: varchar({ length: 7 }).notNull(),
	message_count: integer().default(0).notNull(),
	last_used: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("ix_ai_usage_user_id").using("btree", table.user_id.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [users.id],
			name: "ai_usage_user_id_fkey"
		}).onDelete("cascade"),
	unique("uq_ai_usage_user_month").on(table.user_id, table.year_month),
]);

export const users = pgTable("users", {
	id: varchar().primaryKey().notNull(),
	email: varchar().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("ix_users_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
]);

export const army_lists = pgTable("army_lists", {
	id: serial().primaryKey().notNull(),
	user_id: varchar().notNull(),
	faction_id: integer().notNull(),
	name: varchar().notNull(),
	points: integer().notNull(),
	swc: doublePrecision().notNull(),
	units_json: jsonb().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	description: text(),
	tags: varchar().array().default([""]).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.faction_id],
			foreignColumns: [factions.id],
			name: "army_lists_faction_id_fkey"
		}),
	foreignKey({
			columns: [table.user_id],
			foreignColumns: [users.id],
			name: "army_lists_user_id_fkey"
		}),
]);

export const unit_factions = pgTable("unit_factions", {
	unit_id: integer().notNull(),
	faction_id: integer().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.faction_id],
			foreignColumns: [factions.id],
			name: "unit_factions_faction_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.unit_id],
			foreignColumns: [units.id],
			name: "unit_factions_unit_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.unit_id, table.faction_id], name: "unit_factions_pkey"}),
]);
